export const hardcodedData = [
  {
    companyId: '1',
    companyName: "Company 1",
    email: "company1@example.com",
    contactNo: "1234567890",
    websiteUrl: "https://www.company1.com",
    pointOfContactEmail: "contact1@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '2',
    companyName: "Company 2",
    email: "company2@example.com",
    contactNo: "1234567891",
    websiteUrl: "https://www.company2.com",
    pointOfContactEmail: "contact2@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '3',
    companyName: "Company 3",
    email: "company3@example.com",
    contactNo: "1234567892",
    websiteUrl: "https://www.company3.com",
    pointOfContactEmail: "contact3@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '4',
    companyName: "Company 4",
    email: "company4@example.com",
    contactNo: "1234567893",
    websiteUrl: "https://www.company4.com",
    pointOfContactEmail: "contact4@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '5',
    companyName: "Company 5",
    email: "company5@example.com",
    contactNo: "1234567894",
    websiteUrl: "https://www.company5.com",
    pointOfContactEmail: "contact5@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '6',
    companyName: "Company 6",
    email: "company6@example.com",
    contactNo: "1234567895",
    websiteUrl: "https://www.company6.com",
    pointOfContactEmail: "contact6@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '7',
    companyName: "Company 7",
    email: "company7@example.com",
    contactNo: "1234567896",
    websiteUrl: "https://www.company7.com",
    pointOfContactEmail: "contact7@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '8',
    companyName: "Company 8",
    email: "company8@example.com",
    contactNo: "1234567897",
    websiteUrl: "https://www.company8.com",
    pointOfContactEmail: "contact8@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '9',
    companyName: "Company 9",
    email: "company9@example.com",
    contactNo: "1234567898",
    websiteUrl: "https://www.company9.com",
    pointOfContactEmail: "contact9@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
  {
    companyId: '10',
    companyName: "Company 10",
    email: "company10@example.com",
    contactNo: "1234567899",
    websiteUrl: "https://www.company10.com",
    pointOfContactEmail: "contact10@example.com",
    primaryColour: "#ff5722",
    companyLogo: null,
    masterProduct: null,
  },
];
